language: node_js
install:
  - npm i -g mocha
  - npm i
node_js:
  - "0.10"
  - "0.12"
  - "3"
  - "4"
  - "5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - g++-4.8
script:
  - npm test
